services:
  postgres:
    image: postgres:latest
    env_file:
      - resume/docker.env
    ports:
      - "5433:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    command: -p 5432
    networks:
      - backend

  app:
    container_name: app_resume
    hostname: app_resume
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - resume/docker.env
    volumes:
      - .:/srv/app
    ports:
      - "8000:8000"
    command: gunicorn resume.wsgi:application --bind 0.0.0.0:8000
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "90:90"
    networks:
      - backend

volumes:
  postgresql-data:
  static-data:

networks:
  backend:
    driver: bridge
