# Generated by Django 4.2.8 on 2023-12-13 17:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="güncelleme tarihi"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="oluşturulma tarihi"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="sıra")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=100, verbose_name="slug"
                    ),
                ),
                (
                    "document_text",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="döküman metni",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        default="",
                        upload_to="documents/",
                        verbose_name="dosya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documents",
                "verbose_name_plural": "Document",
            },
        ),
        migrations.CreateModel(
            name="GeneralSettinModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="güncelleme tarihi"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="oluşturulma tarihi"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="isim"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="açıklama"),
                ),
                (
                    "parameter",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="parametre"
                    ),
                ),
            ],
            options={
                "verbose_name": "General Settings",
                "verbose_name_plural": "General Setting",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="güncelleme tarihi"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="oluşturulma tarihi"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="isim"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="",
                        upload_to="images/",
                        verbose_name="resim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Images",
                "verbose_name_plural": "Image",
            },
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="güncelleme tarihi"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="oluşturulma tarihi"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="isim"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="konu"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="mesaj"),
                ),
            ],
            options={
                "verbose_name": "Messages",
                "verbose_name_plural": "Message",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="SkillTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="güncelleme tarihi"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="oluşturulma tarihi"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="isim"
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Types",
                "verbose_name_plural": "Skill Type",
            },
        ),
        migrations.CreateModel(
            name="SocialModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="güncelleme tarihi"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="oluşturulma tarihi"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="sıra")),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Lütfen doğru url adresi giriniz..",
                        verbose_name="link",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="ikon"
                    ),
                ),
            ],
            options={
                "verbose_name": "Socials",
                "verbose_name_plural": "Social",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SkillModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="güncelleme tarihi"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="oluşturulma tarihi"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="sıra")),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="isim"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="açıklama"),
                ),
                (
                    "percent",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="yüzde",
                    ),
                ),
                (
                    "skiltype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.skilltypemodel",
                        verbose_name="skill tipi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skills",
                "verbose_name_plural": "Skill",
                "ordering": ["order"],
            },
        ),
    ]
